---
- name: Install compton
  packer: name=compton-git state=present

- name: Configure compton
  copy: src=files/compton dest=~/.compton backup=yes

- name: Init compton in .xprofile
  blockinfile:
    path: ~/.xprofile
    create: True
    marker: "### {mark} DOTFILES compton ###"
    content: |
      compton --backend glx --vsync opengl-swc -GCb --config ~/.compton &
  when: ansible_user_id != "vagrant"

- name: Init compton in .xprofile [Vagrant]
  blockinfile:
    path: ~/.xprofile
    create: True
    marker: "### {mark} DOTFILES compton ###"
    content: |
      compton -GCb --config ~/.compton &
  when: ansible_user_id == "vagrant"
