---
- name: Install vim
  package: name={{item}} state=present
  with_items:
    - vim
  become: True

- name : Install powerline [Centos]
  pip: name={{item}} state=present
  with_items:
    - powerline-status
  become: True
  when: ansible_distribution == "CentOS"

- name : Install powerline [Archlinux]
  pacman: name={{item}} state=present
  with_items:
    - powerline
    - powerline-vim
    - powerline-fonts
  become: True
  when: ansible_os_family == "Archlinux"

- name : Install powerline [FreeBSD]
  package: name={{item}} state=present
  with_items:
    - py27-powerline-status
  become: True
  when: ansible_os_family == "FreeBSD"

- name: Create .vim dirs
  file: path={{item}} state=directory
  with_items:
    - ~/.vim
    - ~/.vim/bundle
    - ~/.vim/autoload

- name: Configure vim
  template: src=templates/vimrc dest=~/.vimrc backup=yes

- name: Configure pathogen autoload
  copy: src=files/pathogen.vim dest=~/.vim/autoload/pathogen.vim

- name: Clone colorizer
  git:
    repo: https://github.com/lilydjwg/colorizer
    dest: ~/.vim/bundle/colorizer

- name: Clone vim-sleught
  git:
    repo: https://github.com/tpope/vim-sleuth
    dest: ~/.vim/bundle/vim-sleuth

- name: Clone auto-pairs
  git:
    repo: https://github.com/jiangmiao/auto-pairs
    dest: ~/.vim/bundle/auto-pairs
