---
- name: Install neofetch
  packer: name={{item}} state=present
  with_items:
    - w3m
    - neofetch

- name: creates neofetch conf dir
  file: path=~/.config/neofetch state=directory

- name: Configure neofetch
  copy: src=files/config.conf dest=~/.config/neofetch/config.conf

- name: Copy neofetch archlinux img
  copy: src=files/archlinux.png dest=~/.config/neofetch/archlinux.png
