---
- name: Install common packages
  package: name={{item}} state=present
  with_items:
    - curl
    - wget
  become: True

- name: Include CentOS packages [if CentOS]
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Include Archlinux packages [if Archlinux]
  include_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"
