---
- name: Install Desktop packages
  package: name={{item}} state=present
  with_items:
    - xorg-server
    - xorg-xinit
    - lxappearance
    - slop
    - maim
    - feh
    - xclip
    - xorg-xrdb
    - xorg-xfd
    - connman
    - ttf-hack
  become: True

- name: Include Archlinux tasks [if Archlinux] 
  include_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Test if hostname specific tasks exists
  stat: path={{ playbook_dir }}roles/packages-desktop/tasks/{{ ansible_hostname }}.yml
  register: hostname_packages_file

- name: Include node tasks [if exists] 
  include_tasks: "{{ playbook_dir }}roles/packages-desktop/tasks/{{ ansible_hostname }}.yml"
  when: hostname_packages_file.stat.exists
