---
- name: Install termite
  package: name=termite state=present
  become: True

- name: Create termite conf dir
  file: path=~/.config/termite state=directory

- name: Configure termite
  copy: src=files/config dest=~/.config/termite/config backup=yes

