[[snippets]]
  description = "cut zeek log"
  command = "cat <log> | zeek-cut <field>"
  output = ""

[[snippets]]
  description = "zeek|vast: import zeek logs to vast"
  command = "zcat <ZeekLogsPath/*.log.gz | vast import zeek"
  output = ""

[[snippets]]
  description = "zeek|vast: export zeek logs filtered by addr "
  command = " vast export zeek ':addr in <addr>'"
  output = ""


[[snippets]]
  description = "docker clean regex"
  command = "docker rmi (docker images --filter=reference='<regex>' -q)"
  output = ""
